logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}] 
logging.include-application-name=false
logging.level.org.springframework.web=DEBUG

management.endpoints.web.exposure.include=*

management.otlp.tracing.endpoint=http://localhost:4317
management.otlp.tracing.export.enabled=false
management.otlp.tracing.transport=grpc
management.tracing.sampling.probability=1.0

spring.application.name=task-list

spring.cache.cache-names=users,passwords
spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=600s,recordStats

spring.cloud.gcp.firestore.project-id=task-list-project
spring.cloud.gcp.firestore.emulator.enabled=true
spring.cloud.gcp.firestore.emulator.host=localhost:8100
